apiVersion: apps/v1
kind: Deployment
metadata:
  name: easycrud-backend
  labels:
    app: easycrud-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: easycrud-backend
  template:
    metadata:
      labels:
        app: easycrud-backend
    spec:
      containers:
      - name: backend
        image: easycrud-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: easycrud-backend-service
spec:
  type: ClusterIP
  selector:
    app: easycrud-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
